kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster3
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/16"
