version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
    networks:
      - app-network

  nodejs-app:
    image: nginx:alpine
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge